name: Commit Time Stats

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Clone and generate commit time report
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://${TOKEN}@github.com/abhisheknaiidu/commit-time-analyzer.git
          cd commit-time-analyzer
          npm install
          node index.js --username Abhijeet-ist > ../commit_stats.txt

      - name: Insert stats into README
        run: |
          if grep -q "<!--START_SECTION:commits-->" README.md; then
            sed -i '/<!--START_SECTION:commits-->/, /<!--END_SECTION:commits-->/c\
            <!--START_SECTION:commits-->\n'"$(cat commit_stats.txt)"'\n<!--END_SECTION:commits-->' README.md
          else
            echo -e "\n## ‚è∞ Commit Activity\n\n<!--START_SECTION:commits-->\n$(cat commit_stats.txt)\n<!--END_SECTION:commits-->" >> README.md
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update commit time stats" || echo "No changes to commit"
          git push
