name: GitHub Metrics

on:
  schedule: 
    - cron: "0 0 * * *"  # update daily at midnight
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Abhijeet-ist
          template: cosmic
          base: header, activity, community, repositories
          filename: github-metrics.svg
          output_action: commit
          committer_message: "Update GitHub metrics"
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_threshold: 1%
          plugin_stars: true
          plugin_stars_limit: 5
